# Generated by Django 4.1.6 on 2023-02-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='Имя автора записи')),
                ('author_mailbox', models.CharField(max_length=300, verbose_name='Почта автора записи')),
                ('text', models.TextField(max_length=3000, verbose_name='Текст записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время и дата редактирования')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('in blocked', 'Заблокировано')], default='active', max_length=200, verbose_name='Статус')),
            ],
        ),
    ]
